TOURNAMENT_ID = 32916
DEFAULT_MAX_QUESTIONS = 5
DEFAULT_TIMEOUT_SECONDS = 20
DEFAULT_RETRIES = 3
DEFAULT_COOLDOWN_MINUTES = 120
DEFAULT_MIN_PROB = 0.01
DEFAULT_MAX_PROB = 0.99
MODEL_VERSION = "sentinel-v1"
